# Generated by rust2rpm 24
%bcond_without check

%global crate jless

Name:           rust-jless
Version:        0.9.0
Release:        %autorelease
Summary:        Command-line JSON viewer

License:        MIT
URL:            https://crates.io/crates/jless
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          jless-fix-metadata.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A command-line JSON viewer.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%doc RELEASE_CHECKLIST.md
%doc SEARCH.md
%{_bindir}/jless

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
