# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate logos-codegen

Name:           rust-logos-codegen
Version:        0.12.0
Release:        %autorelease
Summary:        Implementation details for logos-codegen and logos-derive

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/logos-codegen
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Implementation details for logos-codegen and logos-derive. Not for
public consumption.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# for now deal with no license files
#%license LICENSE-MIT LICENSE-APACHE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- --lib
%endif

%changelog
%autochangelog
