# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate rustyline-derive

Name:           rust-rustyline-derive
Version:        0.5.0
Release:        %autorelease
Summary:        Rustyline derive macros (Completer, Helper, Hinter, Highlighter)

License:        MIT
URL:            https://crates.io/crates/rustyline-derive
Source0:        %{crates_source}
Source1:        https://github.com/kkawakam/rustyline/raw/v8.2.0/LICENSE

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Rustyline macros implementation of #[derive(Completer, Helper, Hinter,
Highlighter)].}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp -pav %{SOURCE1} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
