# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate rustyline

Name:           rust-rustyline
Version:        9.0.0
Release:        %autorelease
Summary:        Readline implementation based on Antirez's Linenoise

License:        MIT
URL:            https://crates.io/crates/rustyline
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          rustyline-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Rustyline, a readline implementation based on Antirez's Linenoise.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/BUGS.md
%doc %{crate_instdir}/CustomBinding.md
%doc %{crate_instdir}/History.md
%doc %{crate_instdir}/Incremental.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/TODO.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dirs-next-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dirs-next-devel %{_description}

This package contains library source intended for building other packages which
use the "dirs-next" feature of the "%{crate}" crate.

%files       -n %{name}+dirs-next-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+skim-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+skim-devel %{_description}

This package contains library source intended for building other packages which
use the "skim" feature of the "%{crate}" crate.

%files       -n %{name}+skim-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-dirs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-dirs-devel %{_description}

This package contains library source intended for building other packages which
use the "with-dirs" feature of the "%{crate}" crate.

%files       -n %{name}+with-dirs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-fuzzy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-fuzzy-devel %{_description}

This package contains library source intended for building other packages which
use the "with-fuzzy" feature of the "%{crate}" crate.

%files       -n %{name}+with-fuzzy-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
